services:
  app:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
      args:
        - APP_ENV=${APP_ENV}
    container_name: url-shortener-app
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - .env
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly:v1.37.0'
    ulimits:
      memlock: -1
    network_mode: "host"
    volumes:
      - data:/data
volumes:
  data:
