services:
  app:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
      args:
        - APP_ENV=${APP_ENV}
    container_name: url-shortener-app
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - .env
    depends_on:
      dragonfly:
        condition: service_healthy

  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly:v1.37.0'
    ulimits:
      memlock: -1
    network_mode: "host"
    volumes:
      - data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  data:
